[build]
  command = "npm run build"
  publish = "build"
  base = "frontend"

[[redirects]]
  from = "/api/*"
  to = "https://petal-and-hue.onrender.com" 
  status = 200

[[redirects]]
  from = "/images/*"
  to = "https://petal-and-hue.onrender.com"
  status = 200