[build]
  command = "npm run build"
  publish = "build"
  base = "frontend"

[[redirects]]
  from = "/api/*"
  to = "https://snapcart-api.onrender.com/api/:splat" # Make sure this is your correct Render URL
  status = 200