[build]
  command = "npm run build"
  publish = "build"
  base = "frontend"

# This rule forwards API requests
[[redirects]]
  from = "/api/*"
  to = "https://snapcart-api.onrender.com/api/:splat" # Make sure this is your correct Render URL
  status = 200

# ADD THIS NEW RULE to forward image requests
[[redirects]]
  from = "/images/*"
  to = "https://snapcart-api.onrender.com/images/:splat" # Make sure this is your correct Render URL
  status = 200